# Generated by Django 2.2.13 on 2022-10-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('one_hour', models.CharField(max_length=100)),
                ('twentyfour_hour', models.CharField(max_length=100)),
                ('seven_day', models.CharField(max_length=100)),
                ('market_cap', models.CharField(max_length=100)),
                ('volume', models.CharField(max_length=100)),
                ('suppy', models.CharField(max_length=100)),
            ],
        ),
    ]
